scrape_configs:
    - job_name: 'connector'
      static_configs:
          - targets: ['monitoring_prometheus:9090']
    - job_name: 'monitor'
      metrics_path: /probe
      scheme: http
      params:
          module: [http_2xx]
      file_sd_configs:
          - files:
                - /src/targets.yml
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox:9115

alerting:
    alertmanagers:
        - scheme: http
          static_configs:
              - targets: ['monitoring_alertmanager:9093']

rule_files:
    - '/src/alert.rules.yml'